# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kvcache_storage_service_pb2 as kvcache__storage__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvcache_storage_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVCacheStorageServiceStub(object):
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchWrite = channel.unary_unary(
                '/parakv.proto.KVCacheStorageService/BatchWrite',
                request_serializer=kvcache__storage__service__pb2.BatchWriteRequest.SerializeToString,
                response_deserializer=kvcache__storage__service__pb2.BatchWriteResponse.FromString,
                _registered_method=True)
        self.BatchRead = channel.unary_unary(
                '/parakv.proto.KVCacheStorageService/BatchRead',
                request_serializer=kvcache__storage__service__pb2.BatchReadRequest.SerializeToString,
                response_deserializer=kvcache__storage__service__pb2.BatchReadResponse.FromString,
                _registered_method=True)
        self.BatchDelete = channel.unary_unary(
                '/parakv.proto.KVCacheStorageService/BatchDelete',
                request_serializer=kvcache__storage__service__pb2.BatchDeleteRequest.SerializeToString,
                response_deserializer=kvcache__storage__service__pb2.BatchDeleteResponse.FromString,
                _registered_method=True)


class KVCacheStorageServiceServicer(object):
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    """

    def BatchWrite(self, request, context):
        """Batch write a set of KVCache blocks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRead(self, request, context):
        """Batch read a set of KVCache blocks by key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDelete(self, request, context):
        """Batch delete a set of KVCache blocks by key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVCacheStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchWrite,
                    request_deserializer=kvcache__storage__service__pb2.BatchWriteRequest.FromString,
                    response_serializer=kvcache__storage__service__pb2.BatchWriteResponse.SerializeToString,
            ),
            'BatchRead': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRead,
                    request_deserializer=kvcache__storage__service__pb2.BatchReadRequest.FromString,
                    response_serializer=kvcache__storage__service__pb2.BatchReadResponse.SerializeToString,
            ),
            'BatchDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDelete,
                    request_deserializer=kvcache__storage__service__pb2.BatchDeleteRequest.FromString,
                    response_serializer=kvcache__storage__service__pb2.BatchDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parakv.proto.KVCacheStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parakv.proto.KVCacheStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVCacheStorageService(object):
    """-----------------------------------------------------------------------------
    Service
    -----------------------------------------------------------------------------

    """

    @staticmethod
    def BatchWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parakv.proto.KVCacheStorageService/BatchWrite',
            kvcache__storage__service__pb2.BatchWriteRequest.SerializeToString,
            kvcache__storage__service__pb2.BatchWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parakv.proto.KVCacheStorageService/BatchRead',
            kvcache__storage__service__pb2.BatchReadRequest.SerializeToString,
            kvcache__storage__service__pb2.BatchReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parakv.proto.KVCacheStorageService/BatchDelete',
            kvcache__storage__service__pb2.BatchDeleteRequest.SerializeToString,
            kvcache__storage__service__pb2.BatchDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
